---
title: "Merge response variable tables"
output: html_notebook
---


```{r}
# load packages
library(tidyverse)
library(cowplot)

```

1. Import development rate files:
```{r}
# Mariana's desktop
Development <-  read_csv("/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/Development.csv")
Survival <-  read_csv("/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/Survival.csv")
Performance <-  read_csv("/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/Performance.csv")
T0 <- read_csv("/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/T0-G.csv")
```


2. Merge tables 
```{r}
# 1 get all sets and their general info
SetDe <- select(Development, set, sp, family, lifestage, lat, lon, locality, quality)
DeVars <- select(Development, set, Dopt, s_dr, Dlower, Dupper, Dwidth, Max_dr)

SetSu <- select(Survival, set, sp, family, lifestage, lat, lon, locality, quality)
SuVars <- select(Survival, set, maxSopt, minSopt, Slower, Supper, Swidth)

SetPe <- select(Performance, set, sp, family, lifestage, lat, lon, locality, quality)
PeVars <- select(Performance, set, Popt, performance, Plower, Pupper, Pwidth)
#names(T0)
SetT0 <- select(T0, set, sp, family, lifestage, lat, lon, locality, quality)
T0Vars <- select(T0, set, T0, G, slope)

names(Performance)

# 2 merge set info
setInfo1 <- rbind(SetDe, SetSu, SetPe, SetT0)
setInfo <- distinct(setInfo1)
Merge1 <- full_join(DeVars, SuVars, by = "set")
Merge2 <- full_join(Merge1, PeVars, by = "set")
Merge3 <- full_join(Merge2, T0Vars, by = "set")
Responses <- full_join(Merge3, setInfo, by = "set")

```


```{r}
#write_csv(Responses,"/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/ThermalResponsesII.csv")
```

Summary plot
```{r}
responses <- read_csv("/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/ThermalResponsesII.csv")
responses_table <- responses %>% 
  filter(lifestage == "egg"| lifestage == "larva"| lifestage == "pupa") %>% 
  mutate(lifestage = factor(lifestage)) %>% 
  select(sp, lifestage, Popt, Dopt, Sopt = maxSopt)

long_responses <- responses_table %>% 
  pivot_longer(c(`Popt`, `Dopt`, `Sopt`), names_to = "threshold", values_to = "temperature")

ggplot(long_responses, aes(x = threshold, y = temperature))+
  geom_boxplot()+
  
  theme_cowplot()+
  ylim(0,40)+
  facet_grid(.~lifestage)
  
str(responses_table)
```
```{r}
responses_table_w <- responses %>% 
  filter(lifestage == "egg"| lifestage == "larva"| lifestage == "pupa") %>% 
  mutate(lifestage = factor(lifestage)) %>% 
  select(sp, lifestage, Pwidth, Dwidth, Swidth)

long_width <- responses_table_w %>% 
  pivot_longer(c(`Pwidth`, `Dwidth`, `Swidth`), names_to = "threshold", values_to = "temperature")

ggplot(long_width, aes(x = threshold, y = temperature))+
  geom_boxplot()+
  
  theme_cowplot()+
  ylim(0,40)+
  facet_grid(.~lifestage)
  
```

```{r}
responses_table_min <- responses %>% 
  filter(lifestage == "egg"| lifestage == "larva"| lifestage == "pupa") %>% 
  mutate(lifestage = factor(lifestage)) %>% 
  select(sp, lifestage, Plower, Dlower, Slower, T0)

long_min<- responses_table_min %>% 
  pivot_longer(c(`Plower`, `Dlower`, `Slower`, `T0`), names_to = "threshold", values_to = "temperature")

ggplot(long_min, aes(x = threshold, y = temperature))+
  geom_boxplot()+
  
  theme_cowplot()+
  ylim(0,40)+
  facet_grid(.~lifestage)
```

```{r}
responses_table_max <- responses %>% 
  filter(lifestage == "egg"| lifestage == "larva"| lifestage == "pupa") %>% 
  mutate(lifestage = factor(lifestage)) %>% 
  select(sp, lifestage, Pupper, Dupper, Supper)

long_max<- responses_table_max %>% 
  pivot_longer(c(`Pupper`, `Dupper`, `Supper`), names_to = "threshold", values_to = "temperature")

ggplot(long_max, aes(x = threshold, y = temperature))+
  geom_boxplot()+
  
  theme_cowplot()+
  ylim(0,40)+
  facet_grid(.~lifestage)

```

```{r}
responses <- read_csv("/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/ThermalResponsesII.csv")
responses_table <- responses %>% 
  filter(lifestage == "egg"| lifestage == "larva"| lifestage == "pupa") %>% 
  mutate(lifestage = factor(lifestage))
sp_list <- responses_table %>% select(sp, family) %>% distinct()
#write_csv(sp_list,"/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/SpeciesList.csv")

```

