---
title: "T0 and G calculation"
output: html_notebook
---


```{r}
# load packages
library(tidyverse)
library(readxl)
library(cowplot)
library(psych)
library(janitor)
```

Import data 
```{r}
# Mariana's desktop
Data <- read_xlsx("/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/PhysiologyDatabaseVersion5.xlsx", 
                  sheet = "WorkingTable", na = c("NA", ""))
```

```{r}
# Mariana's laptop
Data <- read_xlsx("/Users/mar/Desktop/Projects/ThermalPerformance/PhysiologyDatabaseVersion5.xlsx", 
                  sheet = "WorkingTable", na = c("NA", "")) 

```


```{r}
# Anna's Laptop
Data <- read_xlsx("~/Desktop/PhysiologyDatabaseVersion5.xlsx", 
                  sheet = "WorkingTable", na = c("NA", "")) 

```


```{r}
# Discard parasitoids and change character to factor 
unique(Data$status)
Ana <- Data[Data$status != "parasitoid",]
rm(Data)

# convert character to factor
Ana <- Ana %>%
  mutate_if(is.character, factor)
```


```{r}
set_944 <- filter(Ana, set == 944)
 set_6 <- filter(Ana, set == 6)
 set_70 <- filter(Ana, set == 70)
 trial <- rbind(set_6, set_70, set_944)
 
 
```

Identify "rise" intervals
```{r}
Ana_dr <- Ana %>% 
  filter(!is.na(dr))
Data <- filter(Ana_dr, set == 146)

get_rise_intervals <- function(Data){
  Data <- Data[!is.na(Data$dr) & !is.na(Data$temp),] # Remove treatments with no dr data
  Data <- Data[order(Data$temp),]
  print(paste("set:", Data$set[1]))
  if(nrow(Data) > 2 )
  {
    np <- nrow(Data)# extract number of points
    nl <- np # guess number of lists
    mat <- matrix(list(), nrow = round(sqrt(nl)+1), ncol = np) # ouptput list
    nums <- data.frame()
   # print(paste("nums1 = ", nums))
    i <- 1
    xpre <- Data[1,"temp"][[1]]
    ypre <- Data[1, "dr"][[1]]
    phase <- 0
    j <- 1
    for (index in 2:np) {
      x <- Data[index,"temp"][[1]]
      y <- Data[index, "dr"][[1]]
      #print(paste("<", xpre, ", ", ypre,"> vs", "<",x,", ",y,">"))
      if (y > ypre)
      {
        phase <- 1
        mat[[i,j]] <- c(xpre,ypre)
        #print(paste("    added <", xpre, ", ", ypre,">"))
        if(index == np){
          j = j + 1
          mat[[i,j]] <- c(x,y)
         # print(paste("    added <", x, ", ", y,">"))
          if (length(nums) == 0){
            i = i + 1
            nums <- rbind(nums,j)
          }
        }
        j = j + 1
        
      }
      
      if( (y <= ypre) && (phase == 1)){
        mat[[i,j]] <- c(xpre,ypre)
       # print(paste("    added <", xpre, ", ", ypre,">"))
        nums <- rbind(nums,j)
        j = 1
        i = i + 1
        phase = 0
      }
      xpre = x
      ypre = y
    }
    numLists <- i-1
    # print(paste("nums_end = ", nums))
    # print(paste("numLists = ", numLists))
    # print(paste("j_end = ", j))
    
    intervals <- tibble()
    
    if(numLists > 0){
    for(i in 1:numLists){
      for(j in 1:nums[i,1]){
        (rowData <- tibble(intervalId=i, temp=mat[[i,j]][1], dr=mat[[i,j]][2]) )
        (intervals <- rbind(intervals,rowData))
      } 
    
      
      }
    } else{print("decreasing")}
    (intervals)
      
  }else
  {
    print("SKIPPED DATASET: SINGLE DATAPOINT")
  }
  
}

```


Get rise intervals from all sets
```{r}
trial2 <- select(trial, set, dr, temp, lifestage)
RiseIntervals1 <- Ana_dr %>% 
  mutate(set2 = set) %>% 
  group_by(set2) %>% 
  nest() %>% 
  mutate(riseI = map(data,get_rise_intervals)) 

RiseIntervals <- RiseIntervals1%>% 
  select(set = set2, riseI) %>% 
  unnest(cols = c(riseI))

length(unique(RiseIntervals$set))
Data <- filter(RiseIntervals, set == 1)
# get longest increasing linear interval
get_longest <- function(Data){
  first <- Data %>% group_by(intervalId, set2) %>% tally(sort = T) %>% filter(n > 2)
  if(nrow(first) == 1) {
    max <- first[first$n == max(first$n), "intervalId"]
    max
  } else{
    print(paste("invalid set:", first$set2[1], sep = ""))
  }
  
}



RiseIntervals$set2 <- RiseIntervals$set
longestlist <- RiseIntervals %>% 
  nest() %>% 
  transmute(keep = map(data, get_longest)) %>% 
  unnest(cols = keep) %>% 
  filter(!is.na(intervalId)) %>% 
  mutate(idd = paste(set, intervalId, sep = "-")) %>% 
  select(-keep)
factor(longestlist$idd)

  
longestIds <- (unique(longestlist$idd))
RiseIntervals$idd <- paste(RiseIntervals$set, RiseIntervals$intervalId, sep = "-")

Intervals <- RiseIntervals %>% 
  filter(idd %in% longestIds) %>% 
  select(set, temp, dr)

```



Function to calculate T0

```{r}

get_t0 <- function(Data){
  Data <- Data[!is.na(Data$dr) & !is.na(Data$temp) & Data$dr > 0,] # Remove treatments with no dr data
  if(nrow(Data) > 2 ){
    print(paste("set:",Data$set[1], sep = " "))
    d_opt <- max(Data$dr) # maximum development rate value
    dTopt <- filter(Data, dr == d_opt)[["temp"]] 
    Data <- filter(Data, temp <= dTopt, dr > 0)
    fit <- lm(dr ~ temp, data = Data) # linear regression
    T0 <- as.numeric(- coef(fit)[1]/coef(fit)[2]) # T0 is the x intercept
    Intercept <- coef(fit)[1]
    slope_f <- as.numeric(coef(fit)[2])
    R2 <- signif(as.numeric(summary(fit)$r.squared), digits = 3) #extract r2
    P <- signif(as.numeric(summary(fit)$coefficients[2, 4]),digits = 3) #extract P
    shap <- signif(as.numeric(shapiro.test(fit$residuals)[2]), digits = 3)
    Data$G <- (1/Data$dr) * (Data$temp - as.numeric(as.character(T0)))
    mean_G <- mean(Data$G, na.rm = T)
    mean_temp <- mean(Data$temp, na.rm = T)
    min_temp <- min(Data$temp, na.rm = T)
    max_temp <- max(Data$temp, na.rm = T)
    Output <- tibble(T0 = T0, 
                     slope = slope_f, 
                     N_temp = nrow(Data),
                     spread = max(Data$temp) - min(Data$temp),
                     r2= R2, P = P, shapiro_testP = shap, G = mean_G, 
                     meantemp = mean_temp, 
                     mintemp = min_temp, 
                     maxtemp = max_temp,
                     Intercept = Intercept) 
    #plot = plot(dr~temp, data = Data, main = paste(Data$sp[1], Data$set[1]))
  } else{ print("less than 3 data points")}
}


```


```{r}
# apply get_t0 to Intervals table
Intervals$set2 <- Intervals$set
T0table <- Intervals %>% 
  group_by(set2) %>% 
  nest() %>% 
  mutate(Threshold = map(data,get_t0)) %>% 
  select(set2, Threshold) %>% 
  unnest(cols = Threshold) 
IntervalID <- unique(Intervals$set)



```

```{r}
T0table <- T0table %>% 
  mutate(set = set2) %>% 
  ungroup() %>% 
  select(-set2)

# test
Interval_944 <- filter(Intervals, set == 944)
T0_944 <- filter(T0table, set == 944)
T0_944b <- get_t0(Interval_944)
ggplot(set_944, aes(x = temp, y = dr))+
  geom_point(col = "grey")+
  geom_point(data = Interval_944, mapping = aes(x = temp, y = dr), col = "black")+
  theme_cowplot()+
  #geom_abline(slope = T0_944$slope, xintercept = T0_944$T0)
  #geom_abline(slope = T0_944$slope, yintercept = T0_944$Intercept, xintercept = T0_944$T0)+
  #geom_segment(x = 5, y = 0.01, xend = 30, yend = 0.01)+
  geom_abline(intercept = T0_944$Intercept, slope = T0_944$slope)+
  ggtitle(paste("Shapiro test P=", T0_944$shapiro_testP, ", r2 =", T0_944$r2, ", P =", T0_944$P, sep = ""))+
  xlim(0,40)
#length(unique(Intervals$set))

```


```{r}
# Create master table

part1 <- Ana_dr %>% 
  group_by(set) %>% 
  nest() %>% 
  transmute(original = data)

part2 <- Intervals %>% 
  group_by(set) %>% 
  nest() %>% 
  transmute(interval = data)

part3 <- T0table %>% 
  group_by(set) %>% 
  nest() %>% 
  transmute(model = data)

master1 <- full_join(part2, part3, by = "set")
master <- inner_join(part1, master1, by = "set")


plot_master <- function(original, interval, model){
  ggplot(interval, aes(x = temp, y = dr))+
   geom_point(data = original, mapping = aes(x = temp, y = dr), col = "grey")+
    geom_point(col = "black")+
    theme_cowplot()+
    
    geom_abline(data = model, mapping = aes(intercept = Intercept, slope = slope))+
    ggtitle(paste("Shapiro test P=", model$shapiro_testP, ", r2 =", model$r2, ", P =", model$P, sep = ""))+
    xlim(0,40)
}

master <- master %>% 
  mutate(plot = pmap(list(original, interval, model), plot_master))
mastersets <- unique(master$set)
#master$plot

# keep only sets with valid linear regressions.

validregressions <- part3 %>% 
  unnest(cols =  model) %>% 
  filter(P < 0.05, shapiro_testP > 0.05, spread > 7)

keepsets <- unique(validregressions$set)
discardsets <- setdiff(mastersets, keepsets)

valid_master <- master %>% filter(set %in% keepsets)
not_valid_examples <- master %>% filter(set %in% discardsets)

```

```{r}
valid_master$plot[1:10]
```



```{r}
not_valid_examples$plot[1:10]
not_valid_examples$set[1:10]
```




```{r}
thresholds <- valid_master %>% 
  select(set, model) %>% 
  unnest(cols = model)

#Add info

Info <- Ana_dr %>% 
  select(set, sp, lifestage, family, lat, lon, locality, quality) %>% 
  distinct()

thres <- inner_join(thresholds, Info, by = "set")
#write_csv(thres,"/Users/marianaabarcazama/Desktop/Projects/ThermalPerformance/T0-G.csv")
mainthres <- thres %>% 
  filter(lifestage == "egg"| lifestage == "larva"| lifestage == "pupa") %>% 
  mutate(absLat = abs(lat))
ggplot(mainthres, aes(x = lifestage, y = T0))+
  geom_boxplot()+
  theme_cowplot()

ggplot(mainthres, aes(x = spread, y = T0))+
  geom_point()+
  theme_cowplot()

ggplot(mainthres, aes(x = N_temp, y = T0))+
  geom_point()+
  theme_cowplot()


names(mainthres)
```

```{r}
library(lme4)
library(car)
library("dotwhisker")  # to make coefficient plots
library(sjPlot) #prediction plots
library(sjmisc)
fit <- lmer(T0 ~ lifestage * absLat + (1|sp), data = mainthres)

meannT0temperate <- mainthres %>% 
  select(T0, absLat) %>% 
  ungroup() %>% 
  filter(absLat > 30 & absLat < 50) %>% 
  summarise(mean = mean(T0, na.rm = T), 
            sd = sd(T0, na.rm = T))


Anova(fit)
```

```{r}
dw_plot(fit) +
  geom_vline(xintercept = mean(mainthres$T0, na.rm = T), lty=2)+
  geom_vline(xintercept = 0 ,lty = 3)+
  theme_cowplot()+
  scale_color_viridis_d()+
  theme(legend.position = "none")


plot_model(fit, type = "int")+
  theme_cowplot()+
  scale_color_viridis_d()
```

```{r}
ggplot(mainthres, aes(x = absLat, y = G, col = lifestage))+
  geom_point()+
  theme_cowplot()+
  facet_grid(.~lifestage)
```

```{r}

rateops <- Ana_dr %>% 
  group_by(set) %>% 
  summarise(drmax =max(dr, na.rm = T))

ad <- inner_join(rateops, mainthres, by = "set")
ggplot(ad, aes(x = absLat, y = drmax))+
  geom_point()+
  theme_cowplot()+
  facet_grid(.~lifestage)





```

```{r}

fit2 <- lmer(drmax ~ -1+  lifestage * absLat + (1|family) , data = ad)

fit2
Anova(fit2)


dw_plot(fit2) +
  geom_vline(xintercept = mean(ad$drmax, na.rm = T), lty=2)+
  geom_vline(xintercept = 0 ,lty = 3)+
  theme_cowplot()+
  scale_color_viridis_d()+
  theme(legend.position = "none")


plot_model(fit2, type = "int")+
  theme_cowplot()+
  scale_color_viridis_d()

ggplot(mainthres, aes(x = absLat, y = G, col = lifestage))+
  geom_point()+
  theme_cowplot()+
  facet_grid(.~lifestage)

```

```{r}
larv <- filter(ad, lifestage == "larva")
fit2 <- lm(drmax ~  absLat , data = ad)

fit2
Anova(fit2)


dw_plot(fit2) +
  geom_vline(xintercept = mean(ad$drmax, na.rm = T), lty=2)+
  geom_vline(xintercept = 0 ,lty = 3)+
  theme_cowplot()+
  scale_color_viridis_d()+
  theme(legend.position = "none")


plot_model(fit2, type = "int")+
  theme_cowplot()+
  scale_color_viridis_d()

ggplot(mainthres, aes(x = absLat, y = G, col = lifestage))+
  geom_point()+
  theme_cowplot()+
  facet_grid(.~lifestage)
```

